[package]
name = "aidoku-workspace"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aidoku-runner = { version = "=0.1.0", path = "lib/api" }

[workspace]
members = [
	"lib/api",
	"lib/c-api"
]
