[package]
name = "aidoku-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmer = "2.3.0"
anyhow = "1.0.66"
reqwest = { version = "0.11.12", features = ["blocking"] }
bytes = "1.2.1"
serde_json = "1.0.87"
chrono = "0.4.22"
